create table cities (
	id bigint generated by default as identity primary key,
	created_at timestamp without time zone not null,
	updated_at timestamp without time zone not null,
	name varchar(255) not null unique,
	active boolean not null
);

create table users (
	id bigint generated by default as identity primary key,
	created_at timestamp without time zone not null,
	updated_at timestamp without time zone not null,
	name varchar(100) not null,
	email varchar(100) not null unique,
	phone varchar(20) not null unique,
	password varchar(255) not null,
	role varchar(255) not null,
	active boolean not null,
	constraint chk_users_role
		check (role in ('ADMIN', 'RESTAURANT_OWNER', 'CUSTOMER', 'DELIVERY_PARTNER'))
);

create table restaurants (
	id bigint generated by default as identity primary key,
	created_at timestamp without time zone not null,
	updated_at timestamp without time zone not null,
	name varchar(150) not null,
	address varchar(255) not null,
	status varchar(30) not null,
	active boolean not null,
	city_id bigint not null,
	owner_user_id bigint not null,
	constraint fk_restaurants_city
		foreign key (city_id) references cities (id),
	constraint fk_restaurants_owner
		foreign key (owner_user_id) references users (id),
	constraint chk_restaurants_status
		check (status in ('OPEN', 'CLOSED', 'INACTIVE'))
);

create table delivery_partners (
	id bigint generated by default as identity primary key,
	created_at timestamp without time zone not null,
	updated_at timestamp without time zone not null,
	user_id bigint not null unique,
	city_id bigint not null,
	availability_status varchar(20) not null,
	active boolean not null,
	constraint fk_delivery_partners_user
		foreign key (user_id) references users (id),
	constraint fk_delivery_partners_city
		foreign key (city_id) references cities (id),
	constraint chk_delivery_partners_availability
		check (availability_status in ('AVAILABLE', 'BUSY', 'OFFLINE', 'INACTIVE'))
);

create table menu_items (
	id bigint generated by default as identity primary key,
	created_at timestamp without time zone not null,
	updated_at timestamp without time zone not null,
	name varchar(120) not null,
	description varchar(500),
	price numeric(10, 2) not null,
	stock_quantity integer not null,
	available boolean not null,
	version bigint,
	restaurant_id bigint not null,
	constraint fk_menu_items_restaurant
		foreign key (restaurant_id) references restaurants (id),
	constraint chk_menu_items_price_non_negative
		check (price >= 0),
	constraint chk_menu_items_stock_non_negative
		check (stock_quantity >= 0)
);

create table orders (
	id bigint generated by default as identity primary key,
	created_at timestamp without time zone not null,
	updated_at timestamp without time zone not null,
	customer_user_id bigint not null,
	restaurant_id bigint not null,
	city_id bigint not null,
	status varchar(30) not null,
	payment_status varchar(30) not null,
	total_amount numeric(10, 2) not null,
	delivery_address varchar(255) not null,
	placed_at timestamp without time zone not null,
	accepted_at timestamp without time zone,
	delivered_at timestamp without time zone,
	version bigint,
	constraint fk_orders_customer
		foreign key (customer_user_id) references users (id),
	constraint fk_orders_restaurant
		foreign key (restaurant_id) references restaurants (id),
	constraint fk_orders_city
		foreign key (city_id) references cities (id),
	constraint chk_orders_status
		check (status in ('PLACED', 'ACCEPTED', 'REJECTED', 'PREPARING', 'READY_FOR_PICKUP', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED')),
	constraint chk_orders_payment_status
		check (payment_status in ('PENDING', 'CAPTURED', 'FAILED', 'REFUNDED')),
	constraint chk_orders_total_amount_non_negative
		check (total_amount >= 0)
);

create table order_items (
	id bigint generated by default as identity primary key,
	order_id bigint not null,
	menu_item_id bigint not null,
	item_name_snapshot varchar(120) not null,
	unit_price_snapshot numeric(10, 2) not null,
	quantity integer not null,
	line_total numeric(10, 2) not null,
	constraint fk_order_items_order
		foreign key (order_id) references orders (id),
	constraint fk_order_items_menu_item
		foreign key (menu_item_id) references menu_items (id),
	constraint chk_order_items_quantity_positive
		check (quantity > 0),
	constraint chk_order_items_unit_price_non_negative
		check (unit_price_snapshot >= 0),
	constraint chk_order_items_line_total_non_negative
		check (line_total >= 0)
);

create table payments (
	id bigint generated by default as identity primary key,
	created_at timestamp without time zone not null,
	updated_at timestamp without time zone not null,
	order_id bigint not null unique,
	amount numeric(10, 2) not null,
	payment_method varchar(20) not null,
	status varchar(20) not null,
	transaction_reference varchar(100),
	failure_reason varchar(500),
	paid_at timestamp without time zone,
	constraint fk_payments_order
		foreign key (order_id) references orders (id),
	constraint chk_payments_method
		check (payment_method in ('COD', 'CARD', 'UPI', 'WALLET')),
	constraint chk_payments_status
		check (status in ('PENDING', 'CAPTURED', 'FAILED', 'REFUNDED')),
	constraint chk_payments_amount_non_negative
		check (amount >= 0)
);

create table delivery_assignments (
	id bigint generated by default as identity primary key,
	created_at timestamp without time zone not null,
	updated_at timestamp without time zone not null,
	order_id bigint not null unique,
	delivery_partner_id bigint,
	status varchar(20) not null,
	assigned_at timestamp without time zone not null,
	accepted_at timestamp without time zone,
	rejected_at timestamp without time zone,
	picked_up_at timestamp without time zone,
	delivered_at timestamp without time zone,
	version bigint,
	constraint fk_delivery_assignments_order
		foreign key (order_id) references orders (id),
	constraint fk_delivery_assignments_partner
		foreign key (delivery_partner_id) references delivery_partners (id),
	constraint chk_delivery_assignments_status
		check (status in ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'COMPLETED', 'CANCELLED'))
);

create table rating_reviews (
	id bigint generated by default as identity primary key,
	created_at timestamp without time zone not null,
	updated_at timestamp without time zone not null,
	order_id bigint not null unique,
	customer_user_id bigint not null,
	restaurant_rating integer,
	partner_rating integer,
	review_comment varchar(1000),
	constraint fk_rating_reviews_order
		foreign key (order_id) references orders (id),
	constraint fk_rating_reviews_customer
		foreign key (customer_user_id) references users (id),
	constraint chk_rating_reviews_restaurant_rating
		check (restaurant_rating is null or restaurant_rating between 1 and 5),
	constraint chk_rating_reviews_partner_rating
		check (partner_rating is null or partner_rating between 1 and 5)
);

create table order_status_history (
	id bigint generated by default as identity primary key,
	order_id bigint not null,
	from_status varchar(30),
	to_status varchar(30) not null,
	changed_by_user_id bigint,
	remarks varchar(500),
	changed_at timestamp without time zone not null,
	constraint fk_order_status_history_order
		foreign key (order_id) references orders (id),
	constraint fk_order_status_history_changed_by_user
		foreign key (changed_by_user_id) references users (id),
	constraint chk_order_status_history_from_status
		check (from_status is null or from_status in ('PLACED', 'ACCEPTED', 'REJECTED', 'PREPARING', 'READY_FOR_PICKUP', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED')),
	constraint chk_order_status_history_to_status
		check (to_status in ('PLACED', 'ACCEPTED', 'REJECTED', 'PREPARING', 'READY_FOR_PICKUP', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED'))
);

create index idx_restaurants_city_id on restaurants (city_id);
create index idx_restaurants_owner_user_id on restaurants (owner_user_id);

create index idx_delivery_partners_city_id on delivery_partners (city_id);
create index idx_delivery_partners_city_status_active
	on delivery_partners (city_id, availability_status, active);

create index idx_menu_items_restaurant_id on menu_items (restaurant_id);
create index idx_menu_items_restaurant_available on menu_items (restaurant_id, available);

create index idx_orders_customer_user_id on orders (customer_user_id);
create index idx_orders_restaurant_id on orders (restaurant_id);
create index idx_orders_city_id on orders (city_id);
create index idx_orders_status on orders (status);
create index idx_orders_restaurant_status on orders (restaurant_id, status);
create index idx_orders_placed_at on orders (placed_at);

create index idx_order_items_order_id on order_items (order_id);
create index idx_order_items_menu_item_id on order_items (menu_item_id);

create index idx_payments_status on payments (status);

create index idx_delivery_assignments_partner_id on delivery_assignments (delivery_partner_id);
create index idx_delivery_assignments_status on delivery_assignments (status);

create index idx_rating_reviews_customer_user_id on rating_reviews (customer_user_id);

create index idx_order_status_history_order_id on order_status_history (order_id);
create index idx_order_status_history_changed_at on order_status_history (order_id, changed_at);